/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuction__factory } from "./IAuction__factory";
export { IExchange__factory } from "./IExchange__factory";
