/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  FHEVerifierMock,
  FHEVerifierMockInterface,
} from "../../../contracts/mocks/FHEVerifierMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "ciphertext",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "evaluate",
    outputs: [
      {
        internalType: "bool",
        name: "ok",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "publicAmountOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "publicPrice",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610249806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063331a2b3d14610030575b600080fd5b61004361003e36600461013c565b610064565b60408051931515845260208401929092529082015260600160405180910390f35b6000806000808787878760405160200161008194939291906101a8565b60408051601f1981840301815291905280516020909101209050806100b069021e19e0c9bab2400000826101ca565b6100c290670de0b6b3a76400006101ec565b93506100d6670de0b6b3a7640000826101ca565b6100e19060016101ec565b92506001945050509450945094915050565b60008083601f84011261010557600080fd5b50813567ffffffffffffffff81111561011d57600080fd5b60208301915083602082850101111561013557600080fd5b9250929050565b6000806000806040858703121561015257600080fd5b843567ffffffffffffffff8082111561016a57600080fd5b610176888389016100f3565b9096509450602087013591508082111561018f57600080fd5b5061019c878288016100f3565b95989497509550505050565b8385823760008482016000815283858237600093019283525090949350505050565b6000826101e757634e487b7160e01b600052601260045260246000fd5b500690565b8082018082111561020d57634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220a6302108e5cb8f6ab2f04e7384e83e77db7ca88037e64e8bd648b29f3f55079a64736f6c63430008180033";

type FHEVerifierMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FHEVerifierMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FHEVerifierMock__factory extends ContractFactory {
  constructor(...args: FHEVerifierMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FHEVerifierMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FHEVerifierMock__factory {
    return super.connect(runner) as FHEVerifierMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FHEVerifierMockInterface {
    return new Interface(_abi) as FHEVerifierMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FHEVerifierMock {
    return new Contract(address, _abi, runner) as unknown as FHEVerifierMock;
  }
}
