/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockExchange,
  MockExchangeInterface,
} from "../../../contracts/mocks/MockExchange";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minAmountOut",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "swapExactTokensForTokensSupportingFeeOnTransferTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061024e806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638465770e14610030575b600080fd5b61004361003e366004610198565b610055565b60405190815260200160405180910390f35b6000846001600160a01b0316866001600160a01b0316146100bd5760405162461bcd60e51b815260206004820152601760248201527f6d6f636b20657870656374732073616d6520746f6b656e00000000000000000060448201526064015b60405180910390fd5b6040516323b872dd60e01b81523360048201526001600160a01b038381166024830152604482018690528716906323b872dd906064016020604051808303816000875af1158015610112573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061013691906101ef565b50828410156101725760405162461bcd60e51b8152602060048201526008602482015267736c69707061676560c01b60448201526064016100b4565b5091949350505050565b80356001600160a01b038116811461019357600080fd5b919050565b600080600080600060a086880312156101b057600080fd5b6101b98661017c565b94506101c76020870161017c565b935060408601359250606086013591506101e36080870161017c565b90509295509295909350565b60006020828403121561020157600080fd5b8151801515811461021157600080fd5b939250505056fea26469706673582212206d1834d1bc89aeb20c5e5e95800bbac4fbd5f7b41e4e1a67204fa58881d789e664736f6c63430008180033";

type MockExchangeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockExchangeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockExchange__factory extends ContractFactory {
  constructor(...args: MockExchangeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockExchange & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockExchange__factory {
    return super.connect(runner) as MockExchange__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockExchangeInterface {
    return new Interface(_abi) as MockExchangeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockExchange {
    return new Contract(address, _abi, runner) as unknown as MockExchange;
  }
}
