/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IAuction {
  export type AuctionStruct = {
    id: BigNumberish;
    seller: AddressLike;
    itemName: string;
    itemDescription: string;
    imageURI: string;
    encryptedReservePrice: BytesLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    status: BigNumberish;
    winner: AddressLike;
    winningBid: BigNumberish;
  };

  export type AuctionStructOutput = [
    id: bigint,
    seller: string,
    itemName: string,
    itemDescription: string,
    imageURI: string,
    encryptedReservePrice: string,
    startTime: bigint,
    endTime: bigint,
    status: bigint,
    winner: string,
    winningBid: bigint
  ] & {
    id: bigint;
    seller: string;
    itemName: string;
    itemDescription: string;
    imageURI: string;
    encryptedReservePrice: string;
    startTime: bigint;
    endTime: bigint;
    status: bigint;
    winner: string;
    winningBid: bigint;
  };

  export type BidStruct = {
    bidder: AddressLike;
    encryptedAmount: BytesLike;
    timestamp: BigNumberish;
    revealed: boolean;
    refunded: boolean;
  };

  export type BidStructOutput = [
    bidder: string,
    encryptedAmount: string,
    timestamp: bigint,
    revealed: boolean,
    refunded: boolean
  ] & {
    bidder: string;
    encryptedAmount: string;
    timestamp: bigint;
    revealed: boolean;
    refunded: boolean;
  };
}

export interface EncryptedAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionCounter"
      | "auctions"
      | "bidPayments"
      | "bids"
      | "cancelAuction"
      | "completeReveal"
      | "createAuction"
      | "getAuctionDetails"
      | "getBids"
      | "getMyBids"
      | "getTotalAuctions"
      | "hasBid"
      | "isAuctionEnded"
      | "owner"
      | "pause"
      | "paused"
      | "refunds"
      | "renounceOwnership"
      | "revealBid"
      | "revealBids"
      | "submitBid"
      | "transferOwnership"
      | "unpause"
      | "withdrawRefund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCreated"
      | "AuctionEnded"
      | "BidSubmitted"
      | "OwnershipTransferred"
      | "Paused"
      | "RefundProcessed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bidPayments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeReveal",
    values: [BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, string, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAuctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasBid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuctionEnded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refunds",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealBids",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawRefund",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bidPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMyBids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuctionEnded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRefund",
    data: BytesLike
  ): Result;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    seller: string,
    endTime: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionEndedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    winningBid: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    winningBid: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    winningBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    bidId: BigNumberish
  ];
  export type OutputTuple = [auctionId: bigint, bidder: string, bidId: bigint];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    bidId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedAuction extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedAuction;
  waitForDeployment(): Promise<this>;

  interface: EncryptedAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionCounter: TypedContractMethod<[], [bigint], "view">;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        seller: string;
        itemName: string;
        itemDescription: string;
        imageURI: string;
        encryptedReservePrice: string;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        winner: string;
        winningBid: bigint;
      }
    ],
    "view"
  >;

  bidPayments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  bids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        bidder: string;
        encryptedAmount: string;
        timestamp: bigint;
        revealed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  cancelAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeReveal: TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidIndices: BigNumberish[],
      decryptedAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  createAuction: TypedContractMethod<
    [
      itemName: string,
      itemDescription: string,
      imageURI: string,
      encryptedReservePrice: BytesLike,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getAuctionDetails: TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.AuctionStructOutput],
    "view"
  >;

  getBids: TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.BidStructOutput[]],
    "view"
  >;

  getMyBids: TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.BidStructOutput[]],
    "view"
  >;

  getTotalAuctions: TypedContractMethod<[], [bigint], "view">;

  hasBid: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isAuctionEnded: TypedContractMethod<
    [auctionId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  refunds: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revealBid: TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidIndex: BigNumberish,
      decryptedAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revealBids: TypedContractMethod<
    [auctionId: BigNumberish, decryptedAmounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [auctionId: BigNumberish, encryptedBidAmount: BytesLike],
    [bigint],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawRefund: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        seller: string;
        itemName: string;
        itemDescription: string;
        imageURI: string;
        encryptedReservePrice: string;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        winner: string;
        winningBid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bidPayments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        bidder: string;
        encryptedAmount: string;
        timestamp: bigint;
        revealed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeReveal"
  ): TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidIndices: BigNumberish[],
      decryptedAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      itemName: string,
      itemDescription: string,
      imageURI: string,
      encryptedReservePrice: BytesLike,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuctionDetails"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.AuctionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBids"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyBids"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalAuctions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasBid"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuctionEnded"
  ): TypedContractMethod<[auctionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "refunds"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidIndex: BigNumberish,
      decryptedAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealBids"
  ): TypedContractMethod<
    [auctionId: BigNumberish, decryptedAmounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, encryptedBidAmount: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRefund"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionEnded"
  ): TypedContractEvent<
    AuctionEndedEvent.InputTuple,
    AuctionEndedEvent.OutputTuple,
    AuctionEndedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AuctionCreated(uint256,address,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionEnded(uint256,address,uint256)": TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;
    AuctionEnded: TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;

    "BidSubmitted(uint256,address,uint256)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RefundProcessed(uint256,address,uint256)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
