/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAuction {
  export type AuctionStruct = {
    id: BigNumberish;
    seller: AddressLike;
    itemName: string;
    itemDescription: string;
    imageURI: string;
    encryptedReservePrice: BytesLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    status: BigNumberish;
    winner: AddressLike;
    winningBid: BigNumberish;
  };

  export type AuctionStructOutput = [
    id: bigint,
    seller: string,
    itemName: string,
    itemDescription: string,
    imageURI: string,
    encryptedReservePrice: string,
    startTime: bigint,
    endTime: bigint,
    status: bigint,
    winner: string,
    winningBid: bigint
  ] & {
    id: bigint;
    seller: string;
    itemName: string;
    itemDescription: string;
    imageURI: string;
    encryptedReservePrice: string;
    startTime: bigint;
    endTime: bigint;
    status: bigint;
    winner: string;
    winningBid: bigint;
  };

  export type BidStruct = {
    bidder: AddressLike;
    encryptedAmount: BytesLike;
    timestamp: BigNumberish;
    revealed: boolean;
    refunded: boolean;
  };

  export type BidStructOutput = [
    bidder: string,
    encryptedAmount: string,
    timestamp: bigint,
    revealed: boolean,
    refunded: boolean
  ] & {
    bidder: string;
    encryptedAmount: string;
    timestamp: bigint;
    revealed: boolean;
    refunded: boolean;
  };
}

export interface IAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelAuction"
      | "createAuction"
      | "getAuctionDetails"
      | "getMyBids"
      | "revealBids"
      | "submitBid"
      | "withdrawRefund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCreated"
      | "AuctionEnded"
      | "BidSubmitted"
      | "RefundProcessed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, string, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealBids",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRefund",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRefund",
    data: BytesLike
  ): Result;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    seller: string,
    endTime: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionEndedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    winningBid: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    winningBid: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    winningBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    bidId: BigNumberish
  ];
  export type OutputTuple = [auctionId: bigint, bidder: string, bidId: bigint];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    bidId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAuction extends BaseContract {
  connect(runner?: ContractRunner | null): IAuction;
  waitForDeployment(): Promise<this>;

  interface: IAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAuction: TypedContractMethod<
    [
      itemName: string,
      itemDescription: string,
      imageURI: string,
      encryptedReservePrice: BytesLike,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getAuctionDetails: TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.AuctionStructOutput],
    "view"
  >;

  getMyBids: TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.BidStructOutput[]],
    "view"
  >;

  revealBids: TypedContractMethod<
    [auctionId: BigNumberish, decryptedAmounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [auctionId: BigNumberish, encryptedBidAmount: BytesLike],
    [bigint],
    "payable"
  >;

  withdrawRefund: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      itemName: string,
      itemDescription: string,
      imageURI: string,
      encryptedReservePrice: BytesLike,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuctionDetails"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.AuctionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyBids"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [IAuction.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealBids"
  ): TypedContractMethod<
    [auctionId: BigNumberish, decryptedAmounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, encryptedBidAmount: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawRefund"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionEnded"
  ): TypedContractEvent<
    AuctionEndedEvent.InputTuple,
    AuctionEndedEvent.OutputTuple,
    AuctionEndedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;

  filters: {
    "AuctionCreated(uint256,address,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionEnded(uint256,address,uint256)": TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;
    AuctionEnded: TypedContractEvent<
      AuctionEndedEvent.InputTuple,
      AuctionEndedEvent.OutputTuple,
      AuctionEndedEvent.OutputObject
    >;

    "BidSubmitted(uint256,address,uint256)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "RefundProcessed(uint256,address,uint256)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
  };
}
