/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEVerifierMockInterface extends Interface {
  getFunction(nameOrSignature: "evaluate"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "evaluate",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "evaluate", data: BytesLike): Result;
}

export interface FHEVerifierMock extends BaseContract {
  connect(runner?: ContractRunner | null): FHEVerifierMock;
  waitForDeployment(): Promise<this>;

  interface: FHEVerifierMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  evaluate: TypedContractMethod<
    [ciphertext: BytesLike, metadata: BytesLike],
    [
      [boolean, bigint, bigint] & {
        ok: boolean;
        publicAmountOut: bigint;
        publicPrice: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "evaluate"
  ): TypedContractMethod<
    [ciphertext: BytesLike, metadata: BytesLike],
    [
      [boolean, bigint, bigint] & {
        ok: boolean;
        publicAmountOut: bigint;
        publicPrice: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
