/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SimpleExchangeAdapter,
  SimpleExchangeAdapterInterface,
} from "../../../contracts/adapters/SimpleExchangeAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minAmountOut",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "swapExactTokensForTokensSupportingFeeOnTransferTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610263806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638465770e14610030575b600080fd5b61004361003e3660046101ad565b610055565b60405190815260200160405180910390f35b6000846001600160a01b0316866001600160a01b0316146100bd5760405162461bcd60e51b815260206004820152601e60248201527f616461707465723a20726f757465206e6f7420696d706c656d656e746564000060448201526064015b60405180910390fd5b6040516323b872dd60e01b81523360048201526001600160a01b038381166024830152604482018690528716906323b872dd906064016020604051808303816000875af1158015610112573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101369190610204565b50828410156101875760405162461bcd60e51b815260206004820152601160248201527f616461707465723a20736c69707061676500000000000000000000000000000060448201526064016100b4565b5091949350505050565b80356001600160a01b03811681146101a857600080fd5b919050565b600080600080600060a086880312156101c557600080fd5b6101ce86610191565b94506101dc60208701610191565b935060408601359250606086013591506101f860808701610191565b90509295509295909350565b60006020828403121561021657600080fd5b8151801515811461022657600080fd5b939250505056fea26469706673582212207da84af4f45038443cb1fc80de739e4faca84ef5f56211c473ac190bddaedecf64736f6c63430008180033";

type SimpleExchangeAdapterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SimpleExchangeAdapterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SimpleExchangeAdapter__factory extends ContractFactory {
  constructor(...args: SimpleExchangeAdapterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SimpleExchangeAdapter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): SimpleExchangeAdapter__factory {
    return super.connect(runner) as SimpleExchangeAdapter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SimpleExchangeAdapterInterface {
    return new Interface(_abi) as SimpleExchangeAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SimpleExchangeAdapter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SimpleExchangeAdapter;
  }
}
